# Generated by Django 4.1.7 on 2023-04-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='total_price',
        ),
    ]
