# Generated by Django 4.1.7 on 2023-05-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur')], max_length=20, null=True),
        ),
    ]
